 /*** TRUNCATE & DROP & DELETE **/
 
 --  Drop Database
 
 CREATE DATABASE TEST_NEW
 DROP DATABASE TEST_NEW
 
 --  Drop Table
 
 CREATE TABLE #TABLE (ID INT,NAME VARCHAR(100))
 SELECT * FROM #TABLE
 DROP TABLE #TABLE
 
 -- Truncate Table 
 
 CREATE TABLE #TEST (ID INT,NAME VARCHAR(100))
 
 INSERT INTO #TEST VALUES (1,'Name1')
 INSERT INTO #TEST VALUES (2,'Name2')
 INSERT INTO #TEST VALUES (3,'Name3')
 
 SELECT * FROM #TEST
 
 TRUNCATE TABLE #TEST
 
 -- Delete from Table
  
 CREATE TABLE #TEST (ID INT,NAME VARCHAR(100))
 
 INSERT INTO #TEST VALUES (1,'Name1')
 INSERT INTO #TEST VALUES (2,'Name2')
 INSERT INTO #TEST VALUES (3,'Name3')
 
 SELECT * FROM #TEST
 
 DELETE FROM #TEST WHERE ID = 1
 
 -- Delete Without Where Clause -- 
 
 DELETE FROM #TEST 
 
 