 /*** RENAME STATEMENT **/
 
 -- Db Name 
 
 CREATE DATABASE TEST_NEW
 
 EXEC sp_Rename 'TEST_NEW','TEST_NEW_1','database'
 
 USE TEST_NEW_1
 
 DROP DATABASE TEST_NEW_1
 
 -- Table Name
 
 CREATE TABLE TEST (ID INT IDENTITY , NAME VARCHAR(100))
 
 INSERT INTO TEST VALUES ('X')
 INSERT INTO TEST VALUES ('Y')
 INSERT INTO TEST VALUES ('Z')
 INSERT INTO TEST VALUES ('A')
 
 SELECT * FROM TEST
 
 SP_RENAME 'TEST','TEST_NEW'
 
 SELECT * FROM TEST
 
 SELECT * FROM TEST_NEW
 
 DROP TABLE TEST_NEW
 
 -- Column Name
 CREATE TABLE TEST (ID INT IDENTITY , NAME VARCHAR(100))
 
 INSERT INTO TEST VALUES ('X')
 INSERT INTO TEST VALUES ('Y')
 INSERT INTO TEST VALUES ('Z')
 INSERT INTO TEST VALUES ('A')
 
 SELECT * FROM TEST
 
 EXEC SP_RENAME 'TEST.ID','ID_NEW','COLUMN'
 
 SELECT * FROM TEST
 
 DROP TABLE TEST
 