 /*** ALTER STATEMENT **/

-- ADD New Column
ALTER TABLE TEST_1
ADD TEST VARCHAR(100)

-- Change Column Length
ALTER TABLE TEST_1
ALTER COLUMN TEST VARCHAR(150)

-- Change Column Datatype
ALTER TABLE TEST_1
ALTER COLUMN TEST NVARCHAR(150)
