 /*** INSERT STATEMENT **/
 
 -- Method 1
 CREATE TABLE #TEST (ID INT,NAME VARCHAR(100),LOCATION VARCHAR(100))
 
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (1,'X','XX')
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (2,'K','YY')
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (3,'Z','ZZ')
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (4,'A','AA')
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (5,'B','BB')
 
 SELECT * FROM #TEST where ID =1 and Name='K'
 -- Method 2
 INSERT INTO #TEST VALUES (6,'C','CC')
 INSERT INTO #TEST VALUES (7,'D','DD')
 INSERT INTO #TEST VALUES (8,'EE','E')
 INSERT INTO #TEST VALUES (9,'F','FF')
 ALTER TABLE #TEST DROP COLUMN LOCATION1 
 -- Method 3
 CREATE TABLE #TEST_1 (ID INT,NAME VARCHAR(100),LOCATION VARCHAR(100))
  
 INSERT INTO #TEST_1 (ID,NAME,LOCATION) VALUES (10,'G','GG')
 INSERT INTO #TEST_1 (ID,NAME,LOCATION) VALUES (11,'H','HH')
 INSERT INTO #TEST_1 (ID,NAME,LOCATION) VALUES (12,'I','II')
 INSERT INTO #TEST_1 (ID,NAME,LOCATION) VALUES (13,'J','JJ')
 INSERT INTO #TEST_1 (NAME,LOCATION) VALUES (K,'KK')

 INSERT INTO #TEST
 SELECT * FROM #TEST_1


 SELECT * FROM #TEST
 
 -- Method 4 
 INSERT INTO #TEST (ID,NAME,LOCATION)
 SELECT ID,NAME,LOCATION FROM #TEST_1
  
 -- Method 5
 Select * INTO #TEST_5 FROM #TEST where 1=2
 
 Select * From  #TEST_5
  