 /*** TEMPRORAY TABLES **/
 
 -- Local Temproray Table
 
 CREATE TABLE #TEST (ID INT,NAME VARCHAR(100),LOCATION VARCHAR(100))
 
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (1,'X','XX')
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (2,'Y','YY')
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (3,'Z','ZZ')
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (4,'A','AA')
 INSERT INTO #TEST (ID,NAME,LOCATION) VALUES (5,'B','BB')
 
 SELECT * FROM #TEST
 
 -- Global Temroray Tables 
 
 CREATE TABLE ##TEST (ID INT,NAME VARCHAR(100),LOCATION VARCHAR(100))
 
 INSERT INTO ##TEST (ID,NAME,LOCATION) VALUES (1,'X','XX')
 INSERT INTO ##TEST (ID,NAME,LOCATION) VALUES (2,'Y','YY')
 INSERT INTO ##TEST (ID,NAME,LOCATION) VALUES (3,'Z','ZZ')
 INSERT INTO ##TEST (ID,NAME,LOCATION) VALUES (4,'A','AA')
 INSERT INTO ##TEST (ID,NAME,LOCATION) VALUES (5,'B','BB')
 
 SELECT * FROM ##TEST